apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kkambbaki-alpha-certificate
  namespace: kkambbaki-alpha
spec:
  secretName: kkambbaki-alpha-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - alpha.singun11.wtf
