apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kkambbaki-alpha-certificate
  namespace: kkambbaki-alpha
spec:
  secretName: kkambbaki-alpha-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - alpha.singun11.wtf
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kkambbaki-alpha-ingress-https
  namespace: kkambbaki-alpha
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`alpha.singun11.wtf`)
    kind: Rule
    services:
    - kind: Service
      name: kkambbaki-alpha-nginx-static-svc
      port: 80
  tls:
    secretName: kkambbaki-alpha-certificate
