apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kkambbaki-alpha-postgres
  namespace: kkambbaki-alpha
spec:
  serviceName: "kkambbaki-alpha-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: kkambbaki-alpha-postgres
  template:
    metadata:
      labels:
        app: kkambbaki-alpha-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.4
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: kkambbaki-alpha-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kkambbaki-alpha-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: kkambbaki-alpha-postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256 --auth-local=trust"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"
        - name: PGDATA
          value: "/var/lib/postgresql/data"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi
