apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kkambbaki-alpha-static-pvc
  namespace: kkambbaki-alpha
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kkambbaki-alpha-media-pvc
  namespace: kkambbaki-alpha
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
